learnql::debug::Profiler
std::vector<PerformanceMetrics> learnql::debug::Profiler::metrics_
std::unordered_map<std::string, std::vector<PerformanceMetrics> > learnql::debug::Profiler::operation_metrics_
static Profiler & learnql::debug::Profiler::instance()
Gets the singleton instance.
Referenced by learnql::debug::ScopedProfiler::~ScopedProfiler.
void learnql::debug::Profiler::record(const PerformanceMetrics &metrics)
Records a performance metric.
References metrics.
Referenced by learnql::debug::ScopedProfiler::~ScopedProfiler.
void learnql::debug::Profiler::print_summary() const
Prints a summary of all metrics.
void learnql::debug::Profiler::clear()
Clears all recorded metrics.
const std::vector< PerformanceMetrics > & learnql::debug::Profiler::metrics() const noexcept
Gets all metrics.
Referenced by record.
learnql::debug::Profiler::Profiler()=default
learnql::debug::Profiler::~Profiler()=default
learnql::debug::Profiler::Profiler(const Profiler &)=delete
Profiler & learnql::debug::Profiler::operator=(const Profiler &)=delete