learnql::core::Table
using learnql::core::Table< T, BatchSize >::value_type = T
using learnql::core::Table< T, BatchSize >::primary_key_type = typename T::primary_key_type
using learnql::core::Table< T, BatchSize >::index_type = index::PersistentBTreeIndex<primary_key_type, RecordId>
std::shared_ptr<storage::StorageEngine> learnql::core::Table< T, BatchSize >::storage_
Storage engine (shared).
std::string learnql::core::Table< T, BatchSize >::table_name_
Table name.
std::unique_ptr<index_type> learnql::core::Table< T, BatchSize >::index_
Persistent B-Tree index (primary key).
std::vector<std::unique_ptr<SecondaryIndexBase> > learnql::core::Table< T, BatchSize >::secondary_indexes_
Secondary indexes.
std::size_t learnql::core::Table< T, BatchSize >::count_
Record count.
catalog::SystemCatalog* learnql::core::Table< T, BatchSize >::catalog_
System catalog (not owned).
learnql::core::Table< T, BatchSize >::Table(std::shared_ptr< storage::StorageEngine > storage, std::string table_name, uint64_t root_page_id=0)
Constructs a table.
storage Shared pointer to storage engine table_name Name of the table root_page_id Root page ID for the B-tree index (0 for new table)
Referenced by learnql::core::Table< T, BatchSize >::Iterator::Iterator.
learnql::core::Table< T, BatchSize >::~Table()
Destructor - flushes index.
void learnql::core::Table< T, BatchSize >::insert(const T &record)
Inserts a new record.
record Record to insert std::runtime_error if a record with this primary key already exists
void learnql::core::Table< T, BatchSize >::update(const T &record)
Updates an existing record.
record Record with updated data std::runtime_error if record not found
bool learnql::core::Table< T, BatchSize >::remove(const primary_key_type &key)
Removes a record by primary key.
key Primary key of record to remove true if record was removed, false if not found
std::unique_ptr< T > learnql::core::Table< T, BatchSize >::find(const primary_key_type &key) const
Finds a record by primary key.
key Primary key to search for Pointer to record, or nullptr if not found
bool learnql::core::Table< T, BatchSize >::contains(const primary_key_type &key) const
Checks if a record exists.
key Primary key to check true if record exists
std::optional< RecordId > learnql::core::Table< T, BatchSize >::get_record_id(const primary_key_type &key) const
Gets the RecordId for a given primary key.
key Primary key to look up Optional RecordId if the key exists This is useful for: Populating secondary indexes from existing data Direct page-level operations Custom index implementations Example: autorid=students.get_record_id(1001); if(rid){ secondary_index.insert(student,*rid); }
Table & learnql::core::Table< T, BatchSize >::add_index(const query::Field< T, FieldType > &field, IndexType type)
Adds a secondary index on a field.
FieldType Type of the indexed field field Static Field object (auto-generated by LEARNQL_PROPERTY) type Index type (Unique or MultiValue) Reference to this table for method chaining Creates a persistent secondary index on the specified field. The index is automatically synchronized on all CRUD operations. Example: auto&students=db.table<Student>("students") .add_index(Student::email,IndexType::Unique) .add_index(Student::department,IndexType::MultiValue); //Nowyoucanusefind_by(): autoalice=students.find_by(Student::email,"alice@uni.edu");
bool learnql::core::Table< T, BatchSize >::drop_index(const query::Field< T, FieldType > &field)
Removes a secondary index on a field.
Implementation of Table::drop_index(). FieldType Type of the indexed field field Static Field object true if index was found and removed Example: students.drop_index(Student::email); Must be defined after SystemCatalog is fully defined
References learnql::query::Field< T, FieldType >::expr, learnql::query::expressions::FieldExpr< T, FieldType >::name.
std::optional< T > learnql::core::Table< T, BatchSize >::find_by(const query::Field< T, FieldType > &field, const FieldType &value) const
Finds a single record by indexed field value (unique index).
FieldType Type of the indexed field field Static Field object value Value to search for Optional record if found This method uses a unique secondary index for O(log n) lookup. Example: autoalice=students.find_by(Student::email,"alice@uni.edu"); if(alice){ std::cout<<alice->get_name()<<"\n"; }
std::vector< T > learnql::core::Table< T, BatchSize >::find_all_by(const query::Field< T, FieldType > &field, const FieldType &value) const
Finds all records by indexed field value (multi-value index).
FieldType Type of the indexed field field Static Field object value Value to search for Vector of matching records This method uses a multi-value secondary index for O(log n) lookup. Example: autocs_students=students.find_all_by(Student::department,"CS"); for(constauto&student:cs_students){ std::cout<<student.get_name()<<"\n"; }
std::vector< FieldType > learnql::core::Table< T, BatchSize >::get_unique_values(const query::Field< T, FieldType > &field) const
Gets all unique values from a multi-value indexed field.
FieldType Type of the indexed field field Static Field object Vector of unique field values Example: autodepartments=students.get_unique_values(Student::department); for(constauto&dept:departments){ std::cout<<dept<<"\n"; }
std::vector< T > learnql::core::Table< T, BatchSize >::range_query(const query::Field< T, FieldType > &field, const FieldType &min_value, const FieldType &max_value) const
Performs a range query on an indexed field.
FieldType Type of the indexed field field Static Field object min_value Minimum value (inclusive) max_value Maximum value (exclusive) Vector of matching records Example: autonames_a_m=students.range_query(Student::name,"A","M");
std::size_t learnql::core::Table< T, BatchSize >::size() const noexcept
Gets the number of records in the table.
bool learnql::core::Table< T, BatchSize >::empty() const noexcept
Checks if the table is empty.
void learnql::core::Table< T, BatchSize >::clear()
Clears all records from the table.
ranges::ProxyVector< T, BatchSize > learnql::core::Table< T, BatchSize >::find_if(Predicate pred) const
Finds all records matching a predicate.
Predicate Function type (bool(const T&)) pred Predicate function ProxyVector of matching records (loaded in batches)
Referenced by learnql::core::Table< T, BatchSize >::get_all, learnql::core::Table< T, BatchSize >::where.
ranges::ProxyVector< T, BatchSize > learnql::core::Table< T, BatchSize >::get_all() const
Gets all records.
ProxyVector of all records (loaded in batches)
Referenced by learnql::core::Table< T, BatchSize >::view.
auto learnql::core::Table< T, BatchSize >::where(const ExprType &expr) const
Creates a query builder for this table (for Phase 3).
Implementation of Table::where() for expression templates. Query builder Forward declaration - implementation requires Query.hpp This needs to be defined after Query is fully defined Include Query.hpp before using this method
References learnql::core::Table< T, BatchSize >::find_if.
Referenced by learnql::core::Table< T, BatchSize >::view_where.
auto learnql::core::Table< T, BatchSize >::view() const
Creates a range view of all records (Phase 4).
QueryView of all records This enables using C++20 ranges with the table: autonames=students.view() |std::views::filter([](auto&s){returns.age>20;}) |std::views::transform([](auto&s){returns.name;});
Referenced by learnql::core::Table< T, BatchSize >::all.
auto learnql::core::Table< T, BatchSize >::all() const
Alias for view() - returns all records as a range.
QueryView of all records
auto learnql::core::Table< T, BatchSize >::view_where(const ExprType &expr) const
Creates a range view of records matching an expression.
ExprType Expression type expr Expression to filter with QueryView of matching records Example: autoresults=students.view_where(age>20) |std::views::transform([](auto&s){returns.name;});
const std::string & learnql::core::Table< T, BatchSize >::name() const noexcept
Gets the table name.
Iterator learnql::core::Table< T, BatchSize >::begin() const
Iterator to beginning (with batched loading).
Returns an iterator that loads record IDs in batches, making iteration memory-efficient for large tables.
Iterator learnql::core::Table< T, BatchSize >::end() const
Iterator to end.
void learnql::core::Table< T, BatchSize >::flush()
Flushes all changes to disk.
Flushes primary index, all secondary indexes, and storage engine.
uint64_t learnql::core::Table< T, BatchSize >::get_root_page() const
Gets the root page ID of the table's B-tree index.
Root page ID
Referenced by learnql::core::Database::table.
void learnql::core::Table< T, BatchSize >::set_catalog(catalog::SystemCatalog *catalog)
Sets the system catalog for metadata sync.
catalog Pointer to system catalog (not owned) Called by Database after table creation to enable automatic record count synchronization.
Referenced by learnql::core::Database::table.
Table< T, BatchSize > & learnql::core::Table< T, BatchSize >::add_index(const query::Field< T, FieldType > &field, IndexType type)
Implementation of Table::add_index().
Must be defined after SystemCatalog is fully defined
T learnql::core::Table< T, BatchSize >::load_record(const RecordId &rid) const
Loads a record from storage.
rid Record ID Loaded record std::runtime_error if record cannot be loaded
void learnql::core::Table< T, BatchSize >::sync_catalog_count()
Synchronize record count with system catalog.
Implementation of Table::sync_catalog_count(). Defined after SystemCatalog include to avoid incomplete type error Must be defined after SystemCatalog is fully defined