learnql::query::Query::Iterator
using learnql::query::Query< T, BatchSize >::Iterator::iterator_category = std::forward_iterator_tag
using learnql::query::Query< T, BatchSize >::Iterator::value_type = T
using learnql::query::Query< T, BatchSize >::Iterator::difference_type = std::ptrdiff_t
using learnql::query::Query< T, BatchSize >::Iterator::pointer = const T*
using learnql::query::Query< T, BatchSize >::Iterator::reference = const T&
table_type::Iterator learnql::query::Query< T, BatchSize >::Iterator::it_
table_type::Iterator learnql::query::Query< T, BatchSize >::Iterator::end_
std::function<bool(const T&)> learnql::query::Query< T, BatchSize >::Iterator::predicate_
learnql::query::Query< T, BatchSize >::Iterator::Iterator(typename table_type::Iterator it, typename table_type::Iterator end, std::function< bool(const T &)> pred)
References learnql::query::Query< T, BatchSize >::end.
Referenced by learnql::query::Query< T, BatchSize >::Iterator::operator!=, learnql::query::Query< T, BatchSize >::Iterator::operator++, learnql::query::Query< T, BatchSize >::Iterator::operator++, learnql::query::Query< T, BatchSize >::Iterator::operator==.
reference learnql::query::Query< T, BatchSize >::Iterator::operator*() const
pointer learnql::query::Query< T, BatchSize >::Iterator::operator->() const
Iterator & learnql::query::Query< T, BatchSize >::Iterator::operator++()
References learnql::query::Query< T, BatchSize >::Iterator::Iterator.
Iterator learnql::query::Query< T, BatchSize >::Iterator::operator++(int)
References learnql::query::Query< T, BatchSize >::Iterator::Iterator.
bool learnql::query::Query< T, BatchSize >::Iterator::operator==(const Iterator &other) const
References learnql::query::Query< T, BatchSize >::Iterator::Iterator.
bool learnql::query::Query< T, BatchSize >::Iterator::operator!=(const Iterator &other) const
References learnql::query::Query< T, BatchSize >::Iterator::Iterator.
void learnql::query::Query< T, BatchSize >::Iterator::advance_to_next_match()