learnql::query::GroupBy
using learnql::query::GroupBy< T, GroupKey >::key_extractor_type = std::function<GroupKey(const T&)>
using learnql::query::GroupBy< T, GroupKey >::group_map_type = std::unordered_map<GroupKey, std::vector<T>>
static auto learnql::query::GroupBy< T, GroupKey >::group_by(const Container &records, key_extractor_type key_extractor, AggFunc agg_func)
Performs a group-by operation with custom aggregation.
Container Container type (e.g., vector) AggFunc Aggregation function type records Records to group key_extractor Function to extract group key agg_func Aggregation function Vector of group-by results
Referenced by learnql::query::GroupBy< T, GroupKey >::average_by, learnql::query::GroupBy< T, GroupKey >::count_by, learnql::query::group_by, learnql::query::GroupBy< T, GroupKey >::max_by, learnql::query::GroupBy< T, GroupKey >::min_by, learnql::query::GroupBy< T, GroupKey >::sum_by.
static auto learnql::query::GroupBy< T, GroupKey >::count_by(const Container &records, key_extractor_type key_extractor)
Groups records and counts them.
Container Container type records Records to group key_extractor Function to extract group key Vector of group counts
References learnql::query::GroupBy< T, GroupKey >::group_by.
static auto learnql::query::GroupBy< T, GroupKey >::sum_by(const Container &records, KeyExtractor &&key_extractor, ValueExtractor &&value_extractor)
Groups records and sums a field.
Container Container type KeyExtractor Key extractor callable type ValueExtractor Value extractor callable type records Records to group key_extractor Function to extract group key value_extractor Function to extract value to sum Vector of group sums
References learnql::query::GroupBy< T, GroupKey >::group_by.
static auto learnql::query::GroupBy< T, GroupKey >::average_by(const Container &records, KeyExtractor &&key_extractor, ValueExtractor &&value_extractor)
Groups records and computes average of a field.
Container Container type KeyExtractor Key extractor callable type ValueExtractor Value extractor callable type records Records to group key_extractor Function to extract group key value_extractor Function to extract value to average Vector of group averages
References learnql::query::GroupBy< T, GroupKey >::group_by.
static auto learnql::query::GroupBy< T, GroupKey >::min_by(const Container &records, KeyExtractor &&key_extractor, ValueExtractor &&value_extractor)
Groups records and finds minimum value of a field.
Container Container type KeyExtractor Key extractor callable type ValueExtractor Value extractor callable type records Records to group key_extractor Function to extract group key value_extractor Function to extract value Vector of group minimums
References learnql::query::GroupBy< T, GroupKey >::group_by.
static auto learnql::query::GroupBy< T, GroupKey >::max_by(const Container &records, KeyExtractor &&key_extractor, ValueExtractor &&value_extractor)
Groups records and finds maximum value of a field.
Container Container type KeyExtractor Key extractor callable type ValueExtractor Value extractor callable type records Records to group key_extractor Function to extract group key value_extractor Function to extract value Vector of group maximums
References learnql::query::GroupBy< T, GroupKey >::group_by.