learnql::coroutines::Generator::Iterator
using learnql::coroutines::Generator< T >::Iterator::iterator_category = std::input_iterator_tag
using learnql::coroutines::Generator< T >::Iterator::value_type = T
using learnql::coroutines::Generator< T >::Iterator::difference_type = std::ptrdiff_t
using learnql::coroutines::Generator< T >::Iterator::pointer = const T*
using learnql::coroutines::Generator< T >::Iterator::reference = const T&
Generator* learnql::coroutines::Generator< T >::Iterator::gen_
std::optional<T> learnql::coroutines::Generator< T >::Iterator::current_
learnql::coroutines::Generator< T >::Iterator::Iterator()=default
Referenced by learnql::coroutines::Generator< T >::Iterator::operator!=, learnql::coroutines::Generator< T >::Iterator::operator++, learnql::coroutines::Generator< T >::Iterator::operator++, learnql::coroutines::Generator< T >::Iterator::operator==.
learnql::coroutines::Generator< T >::Iterator::Iterator(Generator *gen)
References learnql::coroutines::Generator< T >::Generator.
reference learnql::coroutines::Generator< T >::Iterator::operator*() const
pointer learnql::coroutines::Generator< T >::Iterator::operator->() const
Iterator & learnql::coroutines::Generator< T >::Iterator::operator++()
References learnql::coroutines::Generator< T >::Iterator::Iterator.
Iterator learnql::coroutines::Generator< T >::Iterator::operator++(int)
References learnql::coroutines::Generator< T >::Iterator::Iterator.
bool learnql::coroutines::Generator< T >::Iterator::operator==(const Iterator &other) const
References learnql::coroutines::Generator< T >::Iterator::Iterator.
bool learnql::coroutines::Generator< T >::Iterator::operator!=(const Iterator &other) const
References learnql::coroutines::Generator< T >::Iterator::Iterator.
void learnql::coroutines::Generator< T >::Iterator::advance()