learnql::catalog::SystemCatalog
friend class core::Database
friend class core::Table
std::shared_ptr<storage::StorageEngine> learnql::catalog::SystemCatalog::storage_
core::ReadOnlyTable<TableMetadata> learnql::catalog::SystemCatalog::tables_table_
core::ReadOnlyTable<FieldMetadata> learnql::catalog::SystemCatalog::fields_table_
core::ReadOnlyTable<IndexMetadata> learnql::catalog::SystemCatalog::indexes_table_
uint64_t learnql::catalog::SystemCatalog::next_field_id_
uint64_t learnql::catalog::SystemCatalog::next_index_id_
learnql::catalog::SystemCatalog::SystemCatalog(std::shared_ptr< storage::StorageEngine > storage, uint64_t sys_tables_root, uint64_t sys_fields_root, uint64_t sys_indexes_root)
Construct system catalog by loading existing system tables.
storage Storage engine sys_tables_root Root page ID for _sys_tables sys_fields_root Root page ID for _sys_fields sys_indexes_root Root page ID for _sys_indexes Used when opening an existing database.
Referenced by operator=, operator=, SystemCatalog, SystemCatalog.
learnql::catalog::SystemCatalog::SystemCatalog(const SystemCatalog &)=delete
References SystemCatalog.
SystemCatalog & learnql::catalog::SystemCatalog::operator=(const SystemCatalog &)=delete
References SystemCatalog.
learnql::catalog::SystemCatalog::SystemCatalog(SystemCatalog &&) noexcept=default
References SystemCatalog.
SystemCatalog & learnql::catalog::SystemCatalog::operator=(SystemCatalog &&) noexcept=default
References SystemCatalog.
const core::ReadOnlyTable< TableMetadata > & learnql::catalog::SystemCatalog::tables() const
Get read-only access to tables metadata.
ReadOnlyTable for querying table metadata
References tables.
Referenced by tables.
const core::ReadOnlyTable< FieldMetadata > & learnql::catalog::SystemCatalog::fields() const
Get read-only access to fields metadata.
ReadOnlyTable for querying field metadata
const core::ReadOnlyTable< IndexMetadata > & learnql::catalog::SystemCatalog::indexes() const
Get read-only access to indexes metadata (NEW!).
ReadOnlyTable for querying index metadata Example: autostudent_indexes=catalog.indexes() .where(IndexMetadata::table=="students"); for(constauto&idx:student_indexes){ std::cout<<idx.field_name<<"(" <<(idx.is_unique?"unique":"multi-value")<<")\n"; }
void learnql::catalog::SystemCatalog::register_table(const TableMetadata &meta, const std::vector< FieldMetadata > &field_metas)
Register a new table in the catalog.
meta Table metadata field_metas Field metadata for the table std::runtime_error if table already exists
void learnql::catalog::SystemCatalog::unregister_table(const std::string &table_name)
Unregister a table from the catalog.
table_name Name of table to remove Removes table metadata and all associated field metadata.
void learnql::catalog::SystemCatalog::update_record_count(const std::string &table_name, std::size_t count)
Update record count for a table.
table_name Name of table count New record count
uint64_t learnql::catalog::SystemCatalog::register_index(const std::string &table_name, const std::string &field_name, const std::string &field_type, bool is_unique, uint64_t root_page_id)
Register a new secondary index in the catalog.
table_name Name of the table field_name Name of the indexed field field_type C++ type name of the field is_unique true for unique index, false for multi-value root_page_id Root page ID of the index B+Tree The assigned index ID
bool learnql::catalog::SystemCatalog::unregister_index(const std::string &table_name, const std::string &field_name)
Unregister a secondary index from the catalog.
table_name Name of the table field_name Name of the indexed field true if index was found and removed
std::vector< IndexMetadata > learnql::catalog::SystemCatalog::get_table_indexes(const std::string &table_name) const
Get all indexes for a specific table.
table_name Name of the table Vector of index metadata
uint64_t learnql::catalog::SystemCatalog::get_tables_root_page() const
Get root page ID for tables table.
uint64_t learnql::catalog::SystemCatalog::get_fields_root_page() const
Get root page ID for fields table.
uint64_t learnql::catalog::SystemCatalog::get_indexes_root_page() const
Get root page ID for indexes table (NEW!).
uint64_t learnql::catalog::SystemCatalog::compute_next_field_id()
Compute next available field ID from existing fields.
Next field ID to use
uint64_t learnql::catalog::SystemCatalog::compute_next_index_id()
Compute next available index ID from existing indexes.
Next index ID to use