learnql::storage::StorageEngine
std::string learnql::storage::StorageEngine::file_path_
Path to database file.
uint64_t learnql::storage::StorageEngine::next_page_id_
Next page ID to allocate.
uint64_t learnql::storage::StorageEngine::free_list_head_
Head of free list.
uint64_t learnql::storage::StorageEngine::sys_tables_root_
Root page ID for _sys_tables.
uint64_t learnql::storage::StorageEngine::sys_fields_root_
Root page ID for _sys_fields.
uint64_t learnql::storage::StorageEngine::sys_indexes_root_
Root page ID for _sys_indexes (NEW!).
std::size_t learnql::storage::StorageEngine::cache_size_
Maximum cache size.
std::unordered_map<uint64_t, Page> learnql::storage::StorageEngine::page_cache_
Page cache.
std::unordered_set<uint64_t> learnql::storage::StorageEngine::dirty_pages_
Set of dirty page IDs.
learnql::storage::StorageEngine::StorageEngine(const std::string &file_path, std::size_t cache_size=64)
Creates or opens a database file.
file_path Path to the database file cache_size Number of pages to cache in memory std::runtime_error if file cannot be opened
Referenced by operator=, operator=, StorageEngine, StorageEngine.
learnql::storage::StorageEngine::~StorageEngine()
Destructor - flushes all dirty pages.
References flush_all.
learnql::storage::StorageEngine::StorageEngine(const StorageEngine &)=delete
References StorageEngine.
StorageEngine & learnql::storage::StorageEngine::operator=(const StorageEngine &)=delete
References StorageEngine.
learnql::storage::StorageEngine::StorageEngine(StorageEngine &&) noexcept=default
References StorageEngine.
StorageEngine & learnql::storage::StorageEngine::operator=(StorageEngine &&) noexcept=default
References StorageEngine.
uint64_t learnql::storage::StorageEngine::allocate_page(PageType type=PageType::DATA)
Allocates a new page.
type Type of page to allocate Page ID of the allocated page Uses free list if available, otherwise allocates new page
References allocate_page, read_page, write_page.
Referenced by allocate_page.
void learnql::storage::StorageEngine::deallocate_page(uint64_t page_id)
Deallocates a page (adds to free list).
page_id ID of the page to deallocate
References learnql::storage::FREE, read_page, write_page.
Page learnql::storage::StorageEngine::read_page(uint64_t page_id)
Reads a page from storage.
page_id ID of the page to read The page std::runtime_error if page cannot be read
References learnql::storage::Page::header, learnql::storage::PageHeader::is_valid, learnql::storage::PAGE_SIZE, learnql::storage::Page::raw_data.
Referenced by allocate_page, deallocate_page.
void learnql::storage::StorageEngine::write_page(uint64_t page_id, const Page &page)
Writes a page to storage.
page_id ID of the page page The page to write
References flush_all.
Referenced by allocate_page, deallocate_page.
void learnql::storage::StorageEngine::flush_all()
Flushes all dirty pages to disk.
References learnql::storage::PAGE_SIZE, learnql::storage::Page::raw_data, learnql::storage::Page::update_checksum.
Referenced by clear_cache, write_page, ~StorageEngine.
void learnql::storage::StorageEngine::flush_page(uint64_t page_id)
Flushes a specific page to disk.
page_id ID of the page to flush
References learnql::storage::PAGE_SIZE, learnql::storage::Page::raw_data, learnql::storage::Page::update_checksum.
uint64_t learnql::storage::StorageEngine::get_page_count() const noexcept
Gets the total number of pages.
Total page count
const std::string & learnql::storage::StorageEngine::get_file_path() const noexcept
Gets the file path.
Path to the database file
void learnql::storage::StorageEngine::clear_cache()
Clears the page cache.
References flush_all.
uint64_t learnql::storage::StorageEngine::get_sys_tables_root() const
Get root page ID for _sys_tables catalog table.
Root page ID, or 0 if not set
uint64_t learnql::storage::StorageEngine::get_sys_fields_root() const
Get root page ID for _sys_fields catalog table.
Root page ID, or 0 if not set
void learnql::storage::StorageEngine::set_sys_tables_root(uint64_t root_page_id)
Set root page ID for _sys_tables catalog table.
root_page_id Root page ID
void learnql::storage::StorageEngine::set_sys_fields_root(uint64_t root_page_id)
Set root page ID for _sys_fields catalog table.
root_page_id Root page ID
uint64_t learnql::storage::StorageEngine::get_sys_indexes_root() const
Get root page ID for _sys_indexes catalog table (NEW!).
Root page ID, or 0 if not set
void learnql::storage::StorageEngine::set_sys_indexes_root(uint64_t root_page_id)
Set root page ID for _sys_indexes catalog table (NEW!).
root_page_id Root page ID
void learnql::storage::StorageEngine::create_new_database()
Creates a new database file with metadata page (version 3 format).
Page 0 Layout (New Format): Offset 0-15: "LearnQL Database" header (16 bytes) Offset 16-23: next_page_id (8 bytes) Offset 24-31: free_list_head (8 bytes) Offset 32-39: sys_tables_root page ID (8 bytes) Offset 40-47: sys_fields_root page ID (8 bytes) Offset 48-51: database version = 3 (4 bytes) [UPDATED from v2] Offset 52-59: created_timestamp (8 bytes) Offset 60-67: sys_indexes_root page ID (8 bytes) [NEW in v3]
void learnql::storage::StorageEngine::load_metadata()
Loads metadata from page 0 (supports v2 and v3 formats).
std::runtime_error if format is invalid or version is incompatible
void learnql::storage::StorageEngine::save_metadata()
Saves metadata to page 0 (supports v2 and v3 formats).
void learnql::storage::StorageEngine::evict_page()
Evicts a page from the cache (LRU-like).