learnql::query::Query
using learnql::query::Query< T, BatchSize >::table_type = core::Table<T, BatchSize>
using learnql::query::Query< T, BatchSize >::value_type = T
table_type& learnql::query::Query< T, BatchSize >::table_
std::function<bool(const T&)> learnql::query::Query< T, BatchSize >::predicate_
learnql::query::Query< T, BatchSize >::Query(table_type &table)
Constructs a query for a table.
table Reference to the table
Referenced by learnql::query::Query< T, BatchSize >::where.
Query & learnql::query::Query< T, BatchSize >::where(const Expr< ExprType > &expr)
Adds a WHERE clause using an expression.
ExprType Expression type expr Expression to filter by Reference to this query (for chaining) Example: query.where((age>18)&&(name=="Alice"));
References learnql::query::expressions::Expr< Derived >::derived, learnql::query::Query< T, BatchSize >::Query.
ranges::ProxyVector< T, BatchSize > learnql::query::Query< T, BatchSize >::execute() const
Executes the query and returns all matching records.
ProxyVector of matching records (loaded in batches)
Referenced by learnql::query::Query< T, BatchSize >::execute_single, learnql::query::Query< T, BatchSize >::operator std::vector< T >.
std::unique_ptr< T > learnql::query::Query< T, BatchSize >::execute_single() const
Executes query and returns the first matching record.
Unique pointer to the first match, or nullptr
References learnql::query::Query< T, BatchSize >::execute.
std::size_t learnql::query::Query< T, BatchSize >::count() const
Counts matching records.
Number of matching records
bool learnql::query::Query< T, BatchSize >::any() const
Checks if any records match the query.
true if at least one record matches
bool learnql::query::Query< T, BatchSize >::all() const
Checks if all records match the query.
true if all records match (or table is empty)
learnql::query::Query< T, BatchSize >::operator std::vector< T >() const
Implicit conversion to vector (executes and materializes the query).
Note: This materializes all results into memory. For large result sets, prefer using the execute() method and iterating over the ProxyVector.
References learnql::query::Query< T, BatchSize >::execute.
Iterator learnql::query::Query< T, BatchSize >::begin() const
Iterator learnql::query::Query< T, BatchSize >::end() const
Referenced by learnql::query::Query< T, BatchSize >::Iterator::Iterator.