learnql::index::PersistentMultiValueSecondaryIndex
using learnql::index::PersistentMultiValueSecondaryIndex< T, FieldType >::getter_type = std::function<FieldType(const T&)>
using learnql::index::PersistentMultiValueSecondaryIndex< T, FieldType >::composite_key_type = CompositeKey<FieldType>
using learnql::index::PersistentMultiValueSecondaryIndex< T, FieldType >::index_type = PersistentBTreeIndex<composite_key_type, core::RecordId>
std::string learnql::index::PersistentMultiValueSecondaryIndex< T, FieldType >::field_name_
Name of the indexed field.
getter_type learnql::index::PersistentMultiValueSecondaryIndex< T, FieldType >::getter_
Function to extract field value.
std::unique_ptr<index_type> learnql::index::PersistentMultiValueSecondaryIndex< T, FieldType >::index_
Underlying B+Tree index.
learnql::index::PersistentMultiValueSecondaryIndex< T, FieldType >::PersistentMultiValueSecondaryIndex(std::string field_name, getter_type getter, std::shared_ptr< storage::StorageEngine > storage, uint64_t root_page_id=0)
Constructs a persistent multi-value secondary index.
field_name Name of the indexed field getter Function to extract field value from record storage Shared pointer to storage engine root_page_id Root page ID (0 for new index)
bool learnql::index::PersistentMultiValueSecondaryIndex< T, FieldType >::insert(const T &record, const core::RecordId &rid)
Inserts a record into the index.
record The record to index rid RecordId of the record true if inserted successfully Uses composite key (field_value, page_id) to ensure uniqueness.
References learnql::core::RecordId::page_id.
std::vector< core::RecordId > learnql::index::PersistentMultiValueSecondaryIndex< T, FieldType >::find(const FieldType &value) const
Finds all records with a given field value.
value Field value to search for Vector of RecordIds with matching field value Uses B+Tree range query to find all composite keys with this field value.
Referenced by learnql::index::PersistentMultiValueSecondaryIndex< T, FieldType >::contains, learnql::index::PersistentMultiValueSecondaryIndex< T, FieldType >::count, learnql::index::PersistentMultiValueSecondaryIndex< T, FieldType >::remove_all.
bool learnql::index::PersistentMultiValueSecondaryIndex< T, FieldType >::contains(const FieldType &value) const
Checks if any record has the given field value.
value Field value to check true if at least one record has this value
References learnql::index::PersistentMultiValueSecondaryIndex< T, FieldType >::find.
std::size_t learnql::index::PersistentMultiValueSecondaryIndex< T, FieldType >::count(const FieldType &value) const
Counts how many records have the given field value.
value Field value to count Number of records with this value
References learnql::index::PersistentMultiValueSecondaryIndex< T, FieldType >::find.
bool learnql::index::PersistentMultiValueSecondaryIndex< T, FieldType >::remove(const T &record, const core::RecordId &rid)
Removes a specific record from the index.
record The record to remove rid RecordId of the record true if removed, false if not found
References learnql::core::RecordId::page_id.
std::size_t learnql::index::PersistentMultiValueSecondaryIndex< T, FieldType >::remove_all(const FieldType &value)
Removes all records with a given field value.
value Field value to remove Number of records removed
References learnql::index::PersistentMultiValueSecondaryIndex< T, FieldType >::find.
bool learnql::index::PersistentMultiValueSecondaryIndex< T, FieldType >::update(const T &old_record, const T &new_record, const core::RecordId &rid)
Updates the index when a record is modified.
old_record The old record state new_record The new record state rid RecordId of the record true if updated successfully Handles the case where the indexed field value changes.
References learnql::core::RecordId::page_id.
std::vector< FieldType > learnql::index::PersistentMultiValueSecondaryIndex< T, FieldType >::get_unique_values() const
Gets all unique field values.
Vector of unique field values in sorted order This scans all entries and extracts unique field values.
std::vector< std::pair< FieldType, core::RecordId > > learnql::index::PersistentMultiValueSecondaryIndex< T, FieldType >::get_all() const
Gets all indexed values and their RecordIds.
Vector of (field_value, RecordId) pairs
std::size_t learnql::index::PersistentMultiValueSecondaryIndex< T, FieldType >::size() const noexcept
Gets the total number of entries in the index.
bool learnql::index::PersistentMultiValueSecondaryIndex< T, FieldType >::empty() const noexcept
Checks if the index is empty.
const std::string & learnql::index::PersistentMultiValueSecondaryIndex< T, FieldType >::get_field_name() const noexcept
Gets the field name.
uint64_t learnql::index::PersistentMultiValueSecondaryIndex< T, FieldType >::get_root_page_id() const noexcept
Gets the root page ID for persistence.
Root page ID of the underlying B+Tree
void learnql::index::PersistentMultiValueSecondaryIndex< T, FieldType >::flush()
Flushes all changes to disk.
void learnql::index::PersistentMultiValueSecondaryIndex< T, FieldType >::clear_cache()
Clears the node cache and flushes.
auto learnql::index::PersistentMultiValueSecondaryIndex< T, FieldType >::create_batch_iterator() const
Creates a batch iterator for the index.
BatchSize Number of entries per batch BatchIterator for efficient traversal Uses B+Tree leaf linking for optimal performance.
References learnql::index::PersistentMultiValueSecondaryIndex< T, FieldType >::create_batch_iterator.
Referenced by learnql::index::PersistentMultiValueSecondaryIndex< T, FieldType >::create_batch_iterator.