learnql::coroutines::Task< void >
using learnql::coroutines::Task< void >::handle_type = std::coroutine_handle<promise_type>
handle_type learnql::coroutines::Task< void >::coro_
learnql::coroutines::Task< void >::Task(handle_type h)
Referenced by learnql::coroutines::Task< void >::promise_type::get_return_object, operator=, operator=, Task, Task.
learnql::coroutines::Task< void >::Task(const Task &)=delete
References Task.
Task & learnql::coroutines::Task< void >::operator=(const Task &)=delete
References Task.
learnql::coroutines::Task< void >::Task(Task &&other) noexcept
References Task.
Task & learnql::coroutines::Task< void >::operator=(Task &&other) noexcept
References Task.
learnql::coroutines::Task< void >::~Task()
awaiter learnql::coroutines::Task< void >::operator co_await()
void learnql::coroutines::Task< void >::get()
bool learnql::coroutines::Task< void >::is_ready() const noexcept