learnql::core::ReadOnlyTable
using learnql::core::ReadOnlyTable< T, BatchSize >::value_type = T
using learnql::core::ReadOnlyTable< T, BatchSize >::primary_key_type = typename T::primary_key_type
friend class catalog::SystemCatalog
std::unique_ptr<Table<T, BatchSize> > learnql::core::ReadOnlyTable< T, BatchSize >::table_
learnql::core::ReadOnlyTable< T, BatchSize >::ReadOnlyTable(std::shared_ptr< storage::StorageEngine > storage, std::string table_name, uint64_t root_page_id=0)
Construct read-only table from storage parameters.
storage Shared pointer to storage engine table_name Name of the table root_page_id Root page ID for the B-tree index (0 for new table)
Referenced by learnql::core::ReadOnlyTable< T, BatchSize >::operator=, learnql::core::ReadOnlyTable< T, BatchSize >::operator=, learnql::core::ReadOnlyTable< T, BatchSize >::ReadOnlyTable, learnql::core::ReadOnlyTable< T, BatchSize >::ReadOnlyTable.
learnql::core::ReadOnlyTable< T, BatchSize >::ReadOnlyTable(const ReadOnlyTable &)=delete
References learnql::core::ReadOnlyTable< T, BatchSize >::ReadOnlyTable.
ReadOnlyTable & learnql::core::ReadOnlyTable< T, BatchSize >::operator=(const ReadOnlyTable &)=delete
References learnql::core::ReadOnlyTable< T, BatchSize >::ReadOnlyTable.
learnql::core::ReadOnlyTable< T, BatchSize >::ReadOnlyTable(ReadOnlyTable &&) noexcept=default
References learnql::core::ReadOnlyTable< T, BatchSize >::ReadOnlyTable.
ReadOnlyTable & learnql::core::ReadOnlyTable< T, BatchSize >::operator=(ReadOnlyTable &&) noexcept=default
References learnql::core::ReadOnlyTable< T, BatchSize >::ReadOnlyTable.
std::optional< T > learnql::core::ReadOnlyTable< T, BatchSize >::find(const primary_key_type &key) const
Find record by primary key.
key Primary key to search for Optional containing record if found
References learnql::core::ReadOnlyTable< T, BatchSize >::find.
Referenced by learnql::core::ReadOnlyTable< T, BatchSize >::find.
bool learnql::core::ReadOnlyTable< T, BatchSize >::contains(const primary_key_type &key) const
Check if record with given key exists.
key Primary key to check true if record exists
ranges::ProxyVector< T, BatchSize > learnql::core::ReadOnlyTable< T, BatchSize >::get_all() const
Get all records with lazy batch loading.
ProxyVector for memory-efficient iteration
ranges::ProxyVector< T, BatchSize > learnql::core::ReadOnlyTable< T, BatchSize >::find_if(Predicate pred) const
Find records matching predicate (lambda function).
Predicate Function type taking const T& and returning bool pred Predicate function ProxyVector of matching records
ranges::ProxyVector< T, BatchSize > learnql::core::ReadOnlyTable< T, BatchSize >::where(const ExprType &expr) const
Filter records using expression template.
ExprType Expression template type expr Expression to evaluate ProxyVector of matching records
ranges::QueryView< T > learnql::core::ReadOnlyTable< T, BatchSize >::view() const
Get range view of all records.
QueryView for use with C++20 ranges
auto learnql::core::ReadOnlyTable< T, BatchSize >::view_where(const ExprType &expr) const
Get range view of records matching expression.
ExprType Expression template type expr Expression to evaluate Filtered QueryView
ranges::QueryView< T > learnql::core::ReadOnlyTable< T, BatchSize >::all() const
Alias for view().
std::size_t learnql::core::ReadOnlyTable< T, BatchSize >::size() const
Get number of records in table.
Record count
bool learnql::core::ReadOnlyTable< T, BatchSize >::empty() const
Check if table is empty.
true if no records
void learnql::core::ReadOnlyTable< T, BatchSize >::insert(const T &)=delete
Insert is not allowed on read-only tables.
void learnql::core::ReadOnlyTable< T, BatchSize >::update(const T &)=delete
Update is not allowed on read-only tables.
void learnql::core::ReadOnlyTable< T, BatchSize >::remove(const primary_key_type &)=delete
Remove is not allowed on read-only tables.
void learnql::core::ReadOnlyTable< T, BatchSize >::clear()=delete
Clear is not allowed on read-only tables.
Table< T, BatchSize > & learnql::core::ReadOnlyTable< T, BatchSize >::internal_table()
Get mutable access to internal table (SystemCatalog only).
Reference to wrapped table
const Table< T, BatchSize > & learnql::core::ReadOnlyTable< T, BatchSize >::internal_table() const
Get const access to internal table (SystemCatalog only).
Const reference to wrapped table