learnql::query::expressions::FieldExpr
using learnql::query::expressions::FieldExpr< T, FieldType >::object_type = T
using learnql::query::expressions::FieldExpr< T, FieldType >::value_type = FieldType
using learnql::query::expressions::FieldExpr< T, FieldType >::getter_type = std::function<FieldType(const T&)>
std::string learnql::query::expressions::FieldExpr< T, FieldType >::name_
getter_type learnql::query::expressions::FieldExpr< T, FieldType >::getter_
learnql::query::expressions::FieldExpr< T, FieldType >::FieldExpr(std::string name, MemberFunc getter)
Constructs a field expression from a member function pointer.
name Field name (for debugging) getter Member function pointer
References learnql::query::expressions::FieldExpr< T, FieldType >::getter, learnql::query::expressions::FieldExpr< T, FieldType >::name.
learnql::query::expressions::FieldExpr< T, FieldType >::FieldExpr(std::string name, getter_type getter)
Constructs a field expression from a getter function.
name Field name getter Getter function
References learnql::query::expressions::FieldExpr< T, FieldType >::getter, learnql::query::expressions::FieldExpr< T, FieldType >::name.
FieldType learnql::query::expressions::FieldExpr< T, FieldType >::evaluate(const T &obj) const
Evaluates the field for a given object.
obj Object to extract field from Field value
const std::string & learnql::query::expressions::FieldExpr< T, FieldType >::name() const noexcept
Gets the field name.
Referenced by learnql::core::Table< T, BatchSize >::add_index, learnql::core::Table< T, BatchSize >::drop_index, learnql::query::expressions::FieldExpr< T, FieldType >::FieldExpr, learnql::query::expressions::FieldExpr< T, FieldType >::FieldExpr, learnql::core::Table< T, BatchSize >::find_all_by, learnql::core::Table< T, BatchSize >::find_by, learnql::core::Table< T, BatchSize >::get_unique_values, learnql::core::Table< T, BatchSize >::range_query.
std::string learnql::query::expressions::FieldExpr< T, FieldType >::to_string() const
Converts to string representation.
const getter_type & learnql::query::expressions::FieldExpr< T, FieldType >::getter() const noexcept
Gets the getter function (for advanced use).
Referenced by learnql::core::Table< T, BatchSize >::add_index, learnql::query::expressions::FieldExpr< T, FieldType >::FieldExpr, learnql::query::expressions::FieldExpr< T, FieldType >::FieldExpr.