learnql::query::expressions::Expr
const Derived & learnql::query::expressions::Expr< Derived >::derived() const noexcept
CRTP accessor to derived class.
Referenced by learnql::query::expressions::Expr< Derived >::evaluate, learnql::query::operator&&, learnql::query::operator||, learnql::query::expressions::Expr< Derived >::to_string, learnql::query::Query< T, BatchSize >::where.
auto learnql::query::expressions::Expr< Derived >::evaluate(const T &obj) const
Evaluates the expression for a given object.
T Object type obj Object to evaluate against Result of evaluation
References learnql::query::expressions::Expr< Derived >::derived.
std::string learnql::query::expressions::Expr< Derived >::to_string() const
Converts expression to a string (for debugging).
References learnql::query::expressions::Expr< Derived >::derived.