learnql::serialization::BinaryWriter
std::vector<uint8_t> learnql::serialization::BinaryWriter::buffer_
Internal buffer.
learnql::serialization::BinaryWriter::BinaryWriter(std::size_t initial_capacity=1024)
Constructs a writer with optional initial capacity.
initial_capacity Initial buffer capacity in bytes
void learnql::serialization::BinaryWriter::write(T value)
Writes an arithmetic type (int, float, etc.).
T Arithmetic type value Value to write @requires T must satisfy Arithmetic concept
References write_raw.
Referenced by learnql::core::Table< T, BatchSize >::insert, learnql::catalog::FieldMetadata::serialize, learnql::catalog::IndexMetadata::serialize, learnql::catalog::TableMetadata::serialize, learnql::core::Table< T, BatchSize >::update, write, write, write.
void learnql::serialization::BinaryWriter::write(const T &str)
Writes a string.
T String-like type str String to write @requires T must satisfy StringLike concept Writes length (as uint32_t) followed by string data
References write, write_raw.
void learnql::serialization::BinaryWriter::write(const Container &container)
Writes a container (vector, list, etc.).
Container Container type container Container to write @requires Container must satisfy Container concept but not StringLike Writes size followed by each element
References size, write.
void learnql::serialization::BinaryWriter::write(const T &obj)
Writes a type with custom serialization.
T Type with custom serialization obj Object to write @requires T must have serialize(BinaryWriter&) method
void learnql::serialization::BinaryWriter::write(const T &ptr)
Writes a smart pointer.
T Smart pointer type ptr Smart pointer to write @requires T must satisfy SmartPointer concept Writes null flag, then data if not null
References write.
void learnql::serialization::BinaryWriter::write_raw(const void *data, std::size_t size)
Writes raw bytes to the buffer.
data Pointer to data size Number of bytes to write
References size.
Referenced by write, write.
void learnql::serialization::BinaryWriter::write_bytes(std::span< const uint8_t > data)
Writes a span of bytes.
data Span of bytes to write
std::span< const uint8_t > learnql::serialization::BinaryWriter::get_buffer() const noexcept
Gets the current buffer.
Span of the buffer
Referenced by learnql::core::Table< T, BatchSize >::insert, learnql::core::Table< T, BatchSize >::update.
std::vector< uint8_t > learnql::serialization::BinaryWriter::take_buffer() noexcept
Gets the buffer as a vector (for moving).
Vector containing the buffer
std::size_t learnql::serialization::BinaryWriter::size() const noexcept
Gets the current size of the buffer.
Size in bytes
Referenced by write, write_raw.
void learnql::serialization::BinaryWriter::clear() noexcept
Clears the buffer.
void learnql::serialization::BinaryWriter::reset(std::size_t capacity=1024)
Resets the buffer with a new capacity.
capacity New capacity
std::size_t learnql::serialization::BinaryWriter::position() const noexcept
Gets the current write position (same as size).
Current position in bytes