learnql::debug::Logger
LogLevel learnql::debug::Logger::min_level_
static Logger & learnql::debug::Logger::instance()
Gets the singleton instance.
void learnql::debug::Logger::set_log_level(LogLevel level)
Sets the minimum log level.
void learnql::debug::Logger::log(LogLevel level, const std::string &message, const std::string &category="")
Logs a message.
References learnql::debug::log_level_to_string.
Referenced by debug, error, info, warn.
void learnql::debug::Logger::debug(const std::string &message, const std::string &category="")
Debug log.
References learnql::debug::Debug, log.
void learnql::debug::Logger::info(const std::string &message, const std::string &category="")
Info log.
References learnql::debug::Info, log.
void learnql::debug::Logger::warn(const std::string &message, const std::string &category="")
Warning log.
References log, learnql::debug::Warning.
void learnql::debug::Logger::error(const std::string &message, const std::string &category="")
Error log.
References learnql::debug::Error, log.
learnql::debug::Logger::Logger()