learnql::ranges::ProxyVector
using learnql::ranges::ProxyVector< T, BatchSize >::BatchFetcher = std::function<std::vector<T>()>
Batch fetcher function type.
This function is called to retrieve the next batch of elements. It should return a vector with up to BatchSize elements, or an empty vector if no more data is available.
using learnql::ranges::ProxyVector< T, BatchSize >::value_type = T
using learnql::ranges::ProxyVector< T, BatchSize >::size_type = std::size_t
using learnql::ranges::ProxyVector< T, BatchSize >::reference = T&
using learnql::ranges::ProxyVector< T, BatchSize >::const_reference = const T&
using learnql::ranges::ProxyVector< T, BatchSize >::pointer = T*
using learnql::ranges::ProxyVector< T, BatchSize >::const_pointer = const T*
using learnql::ranges::ProxyVector< T, BatchSize >::iterator = Iterator
using learnql::ranges::ProxyVector< T, BatchSize >::const_iterator = Iterator
BatchFetcher learnql::ranges::ProxyVector< T, BatchSize >::batch_fetcher_
Function to fetch next batch.
std::vector<T> learnql::ranges::ProxyVector< T, BatchSize >::current_batch_
Current batch in memory.
std::size_t learnql::ranges::ProxyVector< T, BatchSize >::global_pos_
Global position across all batches.
std::size_t learnql::ranges::ProxyVector< T, BatchSize >::batches_loaded_
Number of batches loaded so far.
bool learnql::ranges::ProxyVector< T, BatchSize >::exhausted_
True if all data has been loaded.
learnql::ranges::ProxyVector< T, BatchSize >::ProxyVector(BatchFetcher fetcher)
Constructs a ProxyVector with a batch fetcher.
fetcher Function that returns the next batch of elements The fetcher should return up to BatchSize elements per call, or an empty vector when no more data is available.
Referenced by learnql::ranges::ProxyVector< T, BatchSize >::begin, learnql::ranges::ProxyVector< T, BatchSize >::end.
iterator learnql::ranges::ProxyVector< T, BatchSize >::begin()
Returns an iterator to the beginning.
Iterator pointing to the first element
Referenced by learnql::ranges::ProxyVector< T, BatchSize >::cbegin.
iterator learnql::ranges::ProxyVector< T, BatchSize >::end()
Returns an iterator to the end.
Iterator representing the end of the sequence
Referenced by learnql::ranges::ProxyVector< T, BatchSize >::cend.
const_iterator learnql::ranges::ProxyVector< T, BatchSize >::begin() const
Returns a const iterator to the beginning.
References learnql::ranges::ProxyVector< T, BatchSize >::ProxyVector.
const_iterator learnql::ranges::ProxyVector< T, BatchSize >::end() const
Returns a const iterator to the end.
References learnql::ranges::ProxyVector< T, BatchSize >::ProxyVector.
const_iterator learnql::ranges::ProxyVector< T, BatchSize >::cbegin() const
Returns a const iterator to the beginning.
References learnql::ranges::ProxyVector< T, BatchSize >::begin.
const_iterator learnql::ranges::ProxyVector< T, BatchSize >::cend() const
Returns a const iterator to the end.
References learnql::ranges::ProxyVector< T, BatchSize >::end.
bool learnql::ranges::ProxyVector< T, BatchSize >::empty() const
Checks if the proxy vector is empty.
true if no data is available Note: This loads the first batch to determine if data exists.
std::vector< T > learnql::ranges::ProxyVector< T, BatchSize >::materialize() const
Materializes all remaining data into a std::vector.
Vector containing all elements Use this method when you need all data in memory at once. This defeats the purpose of lazy loading, so use sparingly.
void learnql::ranges::ProxyVector< T, BatchSize >::load_next_batch() const
Loads the next batch of data.
This method is called by the iterator when the current batch is exhausted. The old batch is discarded to free memory.