learnql::core::Database
std::shared_ptr<storage::StorageEngine> learnql::core::Database::storage_
Storage engine (shared with tables).
std::unordered_map<std::type_index, std::shared_ptr<void> > learnql::core::Database::tables_
Type-erased tables (unnamed).
std::unordered_map<std::type_index, std::string> learnql::core::Database::table_names_
Table names (unnamed).
std::unordered_map<std::size_t, std::shared_ptr<void> > learnql::core::Database::named_tables_
Named tables (hash-based).
std::unordered_map<std::size_t, std::string> learnql::core::Database::named_table_names_
Named table names.
std::unique_ptr<catalog::SystemCatalog> learnql::core::Database::catalog_
System catalog for metadata.
learnql::core::Database::Database(const std::string &file_path, std::size_t cache_size=64)
Creates or opens a database.
file_path Path to the database file cache_size Number of pages to cache (default: 64) std::runtime_error if database cannot be opened
Referenced by Database, Database, operator=, operator=, ~Database.
learnql::core::Database::Database(const Database &)=delete
References Database.
Database & learnql::core::Database::operator=(const Database &)=delete
References Database.
learnql::core::Database::Database(Database &&) noexcept=default
References Database.
Database & learnql::core::Database::operator=(Database &&) noexcept=default
References Database.
learnql::core::Database::~Database()
Destructor - flushes all changes.
References Database, flush.
Table< T > & learnql::core::Database::table()
Gets or creates a table for type T.
T Type of objects to store Reference to the table std::runtime_error if table cannot be created The table name is derived from the type name. If the table doesn't exist, it is created automatically. Example: auto&students=db.table<Student>();//Createstableifnotexists students.insert(alice);
Table< T > & learnql::core::Database::table(const std::string &table_name)
Gets a table with a custom name.
T Type of objects to store table_name Name for the table Reference to the table Useful when you want multiple tables of the same type with different names. Example: auto&active_students=db.table<Student>("active_students"); auto&alumni=db.table<Student>("alumni");
References learnql::reflection::extract_field_metadata, learnql::core::Table< T, BatchSize >::get_root_page, learnql::core::Table< T, BatchSize >::set_catalog.
bool learnql::core::Database::has_table() const
Checks if a table exists for type T.
T Type to check true if table exists
void learnql::core::Database::flush()
Flushes all tables to disk.
Referenced by ~Database.
std::size_t learnql::core::Database::table_count() const noexcept
Gets the number of tables.
storage::StorageEngine & learnql::core::Database::get_storage() noexcept
Gets the storage engine.
Reference to the storage engine
const storage::StorageEngine & learnql::core::Database::get_storage() const noexcept
Gets the storage engine (const).
Const reference to the storage engine
std::shared_ptr< storage::StorageEngine > learnql::core::Database::get_storage_ptr() noexcept
Gets the storage engine as a shared pointer.
Shared pointer to the storage engine Use this when you need to create persistent secondary indexes or other components that require shared ownership of the storage. Example: index::PersistentSecondaryIndex<Student,std::string>name_index( "name", [](constStudent&s){returns.get_name();}, db.get_storage_ptr()//Sharedpointerneededhere );
const std::string & learnql::core::Database::get_file_path() const noexcept
Gets the database file path.
std::vector< std::string > learnql::core::Database::get_table_names() const
Gets all table names.
Vector of table names
void learnql::core::Database::drop_table(const std::string &table_name)
Drops a table from the database.
table_name Name of the table to drop std::runtime_error if table is a system table or not found Example: db.drop_table("old_students");
catalog::SystemCatalog & learnql::core::Database::metadata()
Gets the system catalog for querying metadata.
Reference to the system catalog Example: auto&catalog=db.metadata(); autolarge_tables=catalog.tables() .where(catalog::TableMetadata::record_count>1000);
const catalog::SystemCatalog & learnql::core::Database::metadata() const
Gets the system catalog (const version).
static std::string learnql::core::Database::get_table_name()
Generates a table name from type name.
T Type Table name
void learnql::core::Database::initialize_system_catalog()
Initialize system catalog (bootstrap or load).
void learnql::core::Database::bootstrap_system_catalog()
Bootstrap system catalog for new database.
void learnql::core::Database::register_system_table(const std::string &table_name)
Register a system table in the catalog.
T Table metadata type table_name Name of the system table