learnql::coroutines::Generator
using learnql::coroutines::Generator< T >::handle_type = std::coroutine_handle<promise_type>
handle_type learnql::coroutines::Generator< T >::coro_
learnql::coroutines::Generator< T >::Generator(handle_type h)
Constructs a generator from a coroutine handle.
Referenced by learnql::coroutines::Generator< T >::Generator, learnql::coroutines::Generator< T >::Generator, learnql::coroutines::Generator< T >::promise_type::get_return_object, learnql::coroutines::Generator< T >::Iterator::Iterator, learnql::coroutines::Generator< T >::operator=, learnql::coroutines::Generator< T >::operator=.
learnql::coroutines::Generator< T >::Generator(const Generator &)=delete
Deleted copy constructor.
References learnql::coroutines::Generator< T >::Generator.
learnql::coroutines::Generator< T >::Generator(Generator &&other) noexcept
Move constructor.
References learnql::coroutines::Generator< T >::Generator.
Generator & learnql::coroutines::Generator< T >::operator=(const Generator &)=delete
Deleted copy assignment.
References learnql::coroutines::Generator< T >::Generator.
Generator & learnql::coroutines::Generator< T >::operator=(Generator &&other) noexcept
Move assignment.
References learnql::coroutines::Generator< T >::Generator.
learnql::coroutines::Generator< T >::~Generator()
Destructor - destroys the coroutine.
std::optional< T > learnql::coroutines::Generator< T >::next()
Advances the generator and returns the next value.
Optional containing the next value, or empty if done
bool learnql::coroutines::Generator< T >::has_next() const
Checks if the generator has more values.
Iterator learnql::coroutines::Generator< T >::begin()
Returns an iterator to the beginning.
Iterator learnql::coroutines::Generator< T >::end()
Returns an iterator to the end.