learnql::coroutines::Task
using learnql::coroutines::Task< T >::handle_type = std::coroutine_handle<promise_type>
handle_type learnql::coroutines::Task< T >::coro_
learnql::coroutines::Task< T >::Task(handle_type h)
Referenced by learnql::coroutines::Task< T >::promise_type::get_return_object, learnql::coroutines::Task< T >::operator=, learnql::coroutines::Task< T >::operator=, learnql::coroutines::Task< T >::Task, learnql::coroutines::Task< T >::Task.
learnql::coroutines::Task< T >::Task(const Task &)=delete
References learnql::coroutines::Task< T >::Task.
Task & learnql::coroutines::Task< T >::operator=(const Task &)=delete
References learnql::coroutines::Task< T >::Task.
learnql::coroutines::Task< T >::Task(Task &&other) noexcept
References learnql::coroutines::Task< T >::Task.
Task & learnql::coroutines::Task< T >::operator=(Task &&other) noexcept
References learnql::coroutines::Task< T >::Task.
learnql::coroutines::Task< T >::~Task()
awaiter learnql::coroutines::Task< T >::operator co_await()
Makes Task awaitable.
T learnql::coroutines::Task< T >::get()
Gets the result (blocking).
bool learnql::coroutines::Task< T >::is_ready() const noexcept
Checks if the task is complete.