learnql::index::PersistentBTreeIndex
std::size_t learnql::index::PersistentBTreeIndex< Key, Value >::ORDER
std::size_t learnql::index::PersistentBTreeIndex< Key, Value >::MIN_KEYS
std::size_t learnql::index::PersistentBTreeIndex< Key, Value >::MAX_KEYS
std::size_t learnql::index::PersistentBTreeIndex< Key, Value >::CACHE_SIZE
std::shared_ptr<storage::StorageEngine> learnql::index::PersistentBTreeIndex< Key, Value >::storage_
Storage engine.
uint64_t learnql::index::PersistentBTreeIndex< Key, Value >::root_page_id_
Root node page ID.
std::size_t learnql::index::PersistentBTreeIndex< Key, Value >::size_
Number of entries.
std::unordered_map<uint64_t, Node> learnql::index::PersistentBTreeIndex< Key, Value >::node_cache_
Node cache.
std::unordered_set<uint64_t> learnql::index::PersistentBTreeIndex< Key, Value >::dirty_nodes_
Dirty node tracking.
learnql::index::PersistentBTreeIndex< Key, Value >::PersistentBTreeIndex(std::shared_ptr< storage::StorageEngine > storage, uint64_t root_page_id=0)
Constructs a persistent B-tree index.
storage Shared pointer to the storage engine root_page_id Optional root page ID (for loading existing index)
learnql::index::PersistentBTreeIndex< Key, Value >::~PersistentBTreeIndex()
Destructor - flushes all dirty nodes to disk.
bool learnql::index::PersistentBTreeIndex< Key, Value >::insert(const Key &key, const Value &value)
Inserts a key-value pair.
key The key value The value true if inserted, false if key already exists
std::optional< Value > learnql::index::PersistentBTreeIndex< Key, Value >::find(const Key &key) const
Finds a value by key.
key The key to search for Optional containing the value if found
Referenced by learnql::index::PersistentBTreeIndex< primary_key_type, RecordId >::contains.
bool learnql::index::PersistentBTreeIndex< Key, Value >::contains(const Key &key) const
Checks if a key exists.
key The key to check true if key exists
bool learnql::index::PersistentBTreeIndex< Key, Value >::remove(const Key &key)
Removes a key-value pair.
key The key to remove true if removed, false if not found
std::vector< Value > learnql::index::PersistentBTreeIndex< Key, Value >::range_query(const Key &min_key, const Key &max_key) const
Finds all values in a range [min_key, max_key].
min_key Minimum key (inclusive) max_key Maximum key (inclusive) Vector of values in range
std::size_t learnql::index::PersistentBTreeIndex< Key, Value >::size() const noexcept
Gets the number of entries in the index.
bool learnql::index::PersistentBTreeIndex< Key, Value >::empty() const noexcept
Checks if the index is empty.
uint64_t learnql::index::PersistentBTreeIndex< Key, Value >::get_root_page_id() const noexcept
Gets the root page ID (for persistence).
Root page ID
std::vector< std::pair< Key, Value > > learnql::index::PersistentBTreeIndex< Key, Value >::get_all() const
Gets all key-value pairs in sorted order.
Vector of all key-value pairs
BatchIterator< Key, Value, BatchSize > learnql::index::PersistentBTreeIndex< Key, Value >::create_batch_iterator() const
Creates a batch iterator for lazy traversal (B+Tree optimized).
BatchSize Number of entries to fetch per batch BatchIterator configured for this index This method creates a stateful iterator that traverses the B+tree by walking the leaf linked list. This is much more efficient than tree traversal and loads only BatchSize entries at a time. Example: autoiter=index.create_batch_iterator<10>(); while(iter.has_more()){ autobatch=iter.next_batch(); //Processbatch... }
void learnql::index::PersistentBTreeIndex< Key, Value >::flush()
Flushes all dirty nodes to disk.
Must be called to persist changes
Referenced by learnql::index::PersistentBTreeIndex< primary_key_type, RecordId >::clear_cache, learnql::index::PersistentBTreeIndex< primary_key_type, RecordId >::~PersistentBTreeIndex.
void learnql::index::PersistentBTreeIndex< Key, Value >::clear_cache()
Clears the node cache and flushes to disk.
uint64_t learnql::index::PersistentBTreeIndex< Key, Value >::allocate_node(bool is_leaf)
Allocates a new node page.
is_leaf Whether the node is a leaf Page ID of the allocated node
void learnql::index::PersistentBTreeIndex< Key, Value >::deallocate_node(uint64_t page_id)
Deallocates a node page.
page_id Page ID to deallocate
Node learnql::index::PersistentBTreeIndex< Key, Value >::load_node(uint64_t page_id) const
Loads a node from disk (with caching).
page_id Page ID of the node The loaded node
void learnql::index::PersistentBTreeIndex< Key, Value >::save_node(const Node &node)
Saves a node to cache and marks it dirty.
node Node to save
void learnql::index::PersistentBTreeIndex< Key, Value >::write_node_to_page(const Node &node) const
Writes a node to its page.
node Node to write
void learnql::index::PersistentBTreeIndex< Key, Value >::evict_node() const
Evicts a node from the cache (LRU-like).
std::optional< Value > learnql::index::PersistentBTreeIndex< Key, Value >::search(uint64_t node_id, const Key &key) const
Searches for a key starting from a node (B+Tree: always to leaf).
In B+Tree, all values are stored in leaves, so we always traverse to the leaf level even if we encounter the key in an internal node.
bool learnql::index::PersistentBTreeIndex< Key, Value >::insert_non_full(Node &node, const Key &key, const Value &value)
Inserts into a non-full node (B+Tree: values only in leaves).
In B+Tree, data is only stored in leaf nodes. Internal nodes contain routing keys copied from leaves.
void learnql::index::PersistentBTreeIndex< Key, Value >::split_child(Node &parent, std::size_t index)
Splits a full child node (B+Tree version).
B+Tree split behavior: Leaf split: Copy middle key up to parent, keep it in leaf, update leaf links Internal split: Push middle key up to parent (traditional B-tree behavior)
bool learnql::index::PersistentBTreeIndex< Key, Value >::remove_from_node(Node &node, const Key &key)
Removes a key from a node.
In a B+Tree, all actual key-value pairs are stored in leaf nodes. Internal nodes only contain routing keys to guide traversal. Therefore, we should only remove from leaf nodes.
void learnql::index::PersistentBTreeIndex< Key, Value >::range_query_helper(uint64_t node_id, const Key &min_key, const Key &max_key, std::vector< Value > &results) const
Helper for range queries (B+Tree optimized).
In B+Tree, we traverse to the starting leaf, then walk the leaf linked list sequentially. This is much faster than tree traversal.
uint64_t learnql::index::PersistentBTreeIndex< Key, Value >::find_leaf_for_key(uint64_t node_id, const Key &key) const
Finds the leaf node that would contain the given key.
This helper traverses from a starting node to the leaf level, following the appropriate child pointers.
void learnql::index::PersistentBTreeIndex< Key, Value >::traverse(uint64_t node_id, std::vector< std::pair< Key, Value > > &results) const
Traverses all nodes in sorted order (B+Tree optimized).
In B+Tree, all data is in leaves, so we find the leftmost leaf and walk the leaf linked list.
uint64_t learnql::index::PersistentBTreeIndex< Key, Value >::find_leftmost_leaf(uint64_t node_id) const
Finds the leftmost (first) leaf node.
std::size_t learnql::index::PersistentBTreeIndex< Key, Value >::count_entries(uint64_t node_id) const
Counts the number of entries in the index (B+Tree optimized).
In B+Tree, all data is in leaves, so we walk the leaf linked list and count entries in each leaf.