learnql::meta::TypeRegistry
std::unordered_map<std::type_index, TypeInfo> learnql::meta::TypeRegistry::type_info_map_
Map from type to info.
std::unordered_map<std::string, TypeInfo> learnql::meta::TypeRegistry::name_to_info_map_
Map from name to info.
static TypeRegistry & learnql::meta::TypeRegistry::instance()
Gets the singleton instance.
References TypeRegistry.
learnql::meta::TypeRegistry::TypeRegistry(const TypeRegistry &)=delete
References TypeRegistry.
Referenced by instance, operator=, operator=, TypeRegistry, TypeRegistry.
TypeRegistry & learnql::meta::TypeRegistry::operator=(const TypeRegistry &)=delete
References TypeRegistry.
learnql::meta::TypeRegistry::TypeRegistry(TypeRegistry &&)=delete
References TypeRegistry.
TypeRegistry & learnql::meta::TypeRegistry::operator=(TypeRegistry &&)=delete
References TypeRegistry.
void learnql::meta::TypeRegistry::register_type(TypeInfo info)
Registers a type with its metadata.
T Type to register info Type information
void learnql::meta::TypeRegistry::register_type_by_name(const std::string &type_name, TypeInfo info)
Registers a type by name.
type_name Name of the type info Type information
References learnql::meta::type_name.
const TypeInfo & learnql::meta::TypeRegistry::get_type_info() const
Gets type information for a type.
T Type to get info for Type information std::runtime_error if type not registered
const TypeInfo & learnql::meta::TypeRegistry::get_type_info_by_name(const std::string &type_name) const
Gets type information by name.
type_name Name of the type Type information std::runtime_error if type not registered
References learnql::meta::type_name.
bool learnql::meta::TypeRegistry::is_registered() const noexcept
Checks if a type is registered.
T Type to check
bool learnql::meta::TypeRegistry::is_registered(const std::string &type_name) const noexcept
Checks if a type is registered by name.
type_name Name of the type
References learnql::meta::type_name.
std::vector< std::string > learnql::meta::TypeRegistry::get_registered_types() const
Gets all registered type names.
void learnql::meta::TypeRegistry::clear() noexcept
Clears all registered types.
learnql::meta::TypeRegistry::TypeRegistry()=default