learnql::serialization::BinaryReader
std::span<const uint8_t> learnql::serialization::BinaryReader::data_
Data buffer (view).
std::size_t learnql::serialization::BinaryReader::position_
Current read position.
learnql::serialization::BinaryReader::BinaryReader(std::span< const uint8_t > data)
Constructs a reader from a span of bytes.
data Span of bytes to read from
learnql::serialization::BinaryReader::BinaryReader(const std::vector< uint8_t > &data)
Constructs a reader from a vector.
data Vector of bytes to read from
References size.
T learnql::serialization::BinaryReader::read()
Reads an arithmetic type (int, float, etc.).
T Arithmetic type Deserialized value std::runtime_error if not enough data @requires T must satisfy Arithmetic concept
References read_raw.
Referenced by learnql::catalog::FieldMetadata::deserialize, learnql::catalog::IndexMetadata::deserialize, learnql::catalog::TableMetadata::deserialize, read_container, read_smart_ptr, read_string.
std::string learnql::serialization::BinaryReader::read_string()
Reads a string.
Deserialized string std::runtime_error if not enough data Reads length (uint32_t) followed by string data
References read, read_raw, remaining.
Referenced by learnql::catalog::FieldMetadata::deserialize, learnql::catalog::IndexMetadata::deserialize, learnql::catalog::TableMetadata::deserialize, read_container, read_smart_ptr.
Container learnql::serialization::BinaryReader::read_container()
Reads a container (vector, etc.).
Container Container type to read into Deserialized container std::runtime_error if not enough data @requires Container must satisfy Container concept
References read, read_custom, read_string, size.
T learnql::serialization::BinaryReader::read_custom()
Reads a type with custom deserialization.
T Type with custom serialization Deserialized object @requires T must have deserialize(BinaryReader&) method
Referenced by read_container, read_smart_ptr.
T learnql::serialization::BinaryReader::read_smart_ptr()
Reads a smart pointer.
T Smart pointer type Deserialized smart pointer (may be null) @requires T must satisfy SmartPointer concept
References read, read_custom, read_string.
void learnql::serialization::BinaryReader::read_raw(void *dest, std::size_t size)
Reads raw bytes from the buffer.
dest Destination buffer size Number of bytes to read std::runtime_error if not enough data
References size.
Referenced by read, read_string.
std::span< const uint8_t > learnql::serialization::BinaryReader::read_bytes(std::size_t size)
Reads a span of bytes.
size Number of bytes to read Span of read bytes (view into original buffer) std::runtime_error if not enough data
References size.
std::size_t learnql::serialization::BinaryReader::position() const noexcept
Gets the current read position.
Current position in bytes
std::size_t learnql::serialization::BinaryReader::size() const noexcept
Gets the total size of the buffer.
Size in bytes
Referenced by BinaryReader, read_bytes, read_container, read_raw.
std::size_t learnql::serialization::BinaryReader::remaining() const noexcept
Gets the number of remaining bytes.
Number of bytes remaining
Referenced by read_string.
bool learnql::serialization::BinaryReader::has_more() const noexcept
Checks if there are more bytes to read.
true if more data is available
void learnql::serialization::BinaryReader::seek(std::size_t pos)
Seeks to a specific position.
pos Position to seek to std::out_of_range if position is beyond buffer size
void learnql::serialization::BinaryReader::reset() noexcept
Resets the read position to the beginning.
void learnql::serialization::BinaryReader::skip(std::size_t count)
Skips a number of bytes.
count Number of bytes to skip std::runtime_error if skip would exceed buffer size