learnql::storage::Page
std::size_t learnql::storage::Page::DATA_SIZE
Size of data section.
Referenced by available_space, read_data, write_data.
PageHeader learnql::storage::Page::header_
Page metadata.
std::array<uint8_t, DATA_SIZE> learnql::storage::Page::data_
Page data section.
learnql::storage::Page::Page() noexcept
Default constructor - creates a free page.
Referenced by operator=, operator=, Page, Page.
learnql::storage::Page::Page(uint64_t page_id, PageType type=PageType::DATA) noexcept
Constructs a page with specific type and ID.
page_id Unique page identifier type Type of page
References learnql::storage::DATA.
learnql::storage::Page::Page(const Page &)=default
References Page.
Page & learnql::storage::Page::operator=(const Page &)=default
References Page.
learnql::storage::Page::Page(Page &&) noexcept=default
References Page.
Page & learnql::storage::Page::operator=(Page &&) noexcept=default
References Page.
PageHeader & learnql::storage::Page::header() noexcept
Gets the page header.
Reference to the header
References header.
Referenced by header, learnql::storage::StorageEngine::read_page.
const PageHeader & learnql::storage::Page::header() const noexcept
Gets the page header (const).
Const reference to the header
std::span< uint8_t > learnql::storage::Page::data() noexcept
Gets a view of the data section.
std::span providing safe access to data
std::span< const uint8_t > learnql::storage::Page::data() const noexcept
Gets a view of the data section (const).
std::span providing safe read-only access to data
void learnql::storage::Page::write_data(std::size_t offset, const void *src, std::size_t size)
Writes data to the page.
offset Offset in data section to write to src Source data size Number of bytes to write std::out_of_range if offset + size exceeds page size
References DATA_SIZE.
void learnql::storage::Page::read_data(std::size_t offset, void *dest, std::size_t size) const
Reads data from the page.
offset Offset in data section to read from dest Destination buffer size Number of bytes to read std::out_of_range if offset + size exceeds page size
References DATA_SIZE.
void learnql::storage::Page::clear() noexcept
Clears the page (resets to free state).
std::size_t learnql::storage::Page::available_space() const noexcept
Calculates available free space in bytes.
Number of bytes available
References DATA_SIZE.
Referenced by can_fit.
bool learnql::storage::Page::can_fit(std::size_t size) const noexcept
Checks if the page can fit data of given size.
size Size in bytes true if data fits
References available_space.
const void * learnql::storage::Page::raw_data() const noexcept
Gets raw pointer to page data (for I/O operations).
Pointer to beginning of page (header)
Referenced by learnql::storage::StorageEngine::flush_all, learnql::storage::StorageEngine::flush_page, learnql::storage::StorageEngine::read_page.
void * learnql::storage::Page::raw_data() noexcept
Gets raw pointer to page data (for I/O operations).
Pointer to beginning of page (header)
uint32_t learnql::storage::Page::compute_checksum() const noexcept
Computes CRC32 checksum of page data.
Checksum value
Referenced by update_checksum, validate_checksum.
void learnql::storage::Page::update_checksum() noexcept
Updates the checksum in the header.
References compute_checksum.
Referenced by learnql::storage::StorageEngine::flush_all, learnql::storage::StorageEngine::flush_page.
bool learnql::storage::Page::validate_checksum() const noexcept
Validates the checksum.
true if checksum is valid
References compute_checksum.