learnql::query::Field
using learnql::query::Field< T, FieldType >::field_expr_type = FieldExpr<T, FieldType>
field_expr_type learnql::query::Field< T, FieldType >::expr_
learnql::query::Field< T, FieldType >::Field(std::string name, MemberFunc getter)
Constructs a field from a member function pointer.
name Field name (for debugging) getter Member function pointer
Referenced by learnql::query::Field< T, FieldType >::operator!=, learnql::query::Field< T, FieldType >::operator<, learnql::query::Field< T, FieldType >::operator<=, learnql::query::Field< T, FieldType >::operator==, learnql::query::Field< T, FieldType >::operator>, learnql::query::Field< T, FieldType >::operator>=.
learnql::query::Field< T, FieldType >::Field(std::string name, std::function< FieldType(const T &)> getter)
Constructs a field from a getter function.
name Field name getter Getter function
const field_expr_type & learnql::query::Field< T, FieldType >::expr() const noexcept
Gets the underlying field expression.
Referenced by learnql::core::Table< T, BatchSize >::add_index, learnql::core::Table< T, BatchSize >::drop_index, learnql::core::Table< T, BatchSize >::find_all_by, learnql::core::Table< T, BatchSize >::find_by, learnql::core::Table< T, BatchSize >::get_unique_values, learnql::query::Field< T, FieldType >::operator!=, learnql::query::Field< T, FieldType >::operator<, learnql::query::Field< T, FieldType >::operator<=, learnql::query::Field< T, FieldType >::operator==, learnql::query::Field< T, FieldType >::operator>, learnql::query::Field< T, FieldType >::operator>=, learnql::core::Table< T, BatchSize >::range_query.
learnql::query::Field< T, FieldType >::operator const field_expr_type &() const noexcept
Implicit conversion to field expression.
auto learnql::query::Field< T, FieldType >::operator==(const char *value) const
Equality comparison with C-string literal: field == "value".
auto learnql::query::Field< T, FieldType >::operator==(const U &value) const
Equality comparison: field == value.
auto learnql::query::Field< T, FieldType >::operator==(const Field< T, U > &other) const
Field-to-field equality: field == other_field.
References learnql::query::Field< T, FieldType >::expr, learnql::query::Field< T, FieldType >::Field.
auto learnql::query::Field< T, FieldType >::operator!=(const char *value) const
Inequality comparison with C-string literal: field != "value".
auto learnql::query::Field< T, FieldType >::operator!=(const U &value) const
Inequality comparison: field != value.
auto learnql::query::Field< T, FieldType >::operator!=(const Field< T, U > &other) const
Field-to-field inequality: field != other_field.
References learnql::query::Field< T, FieldType >::expr, learnql::query::Field< T, FieldType >::Field.
auto learnql::query::Field< T, FieldType >::operator<(const U &value) const
Less-than comparison: field < value.
auto learnql::query::Field< T, FieldType >::operator<(const Field< T, U > &other) const
Field-to-field less-than: field < other_field.
References learnql::query::Field< T, FieldType >::expr, learnql::query::Field< T, FieldType >::Field.
auto learnql::query::Field< T, FieldType >::operator<=(const U &value) const
Less-than-or-equal comparison: field <= value.
auto learnql::query::Field< T, FieldType >::operator<=(const Field< T, U > &other) const
Field-to-field less-than-or-equal: field <= other_field.
References learnql::query::Field< T, FieldType >::expr, learnql::query::Field< T, FieldType >::Field.
auto learnql::query::Field< T, FieldType >::operator>(const U &value) const
Greater-than comparison: field > value.
auto learnql::query::Field< T, FieldType >::operator>(const Field< T, U > &other) const
Field-to-field greater-than: field > other_field.
References learnql::query::Field< T, FieldType >::expr, learnql::query::Field< T, FieldType >::Field.
auto learnql::query::Field< T, FieldType >::operator>=(const U &value) const
Greater-than-or-equal comparison: field >= value.
auto learnql::query::Field< T, FieldType >::operator>=(const Field< T, U > &other) const
Field-to-field greater-than-or-equal: field >= other_field.
References learnql::query::Field< T, FieldType >::expr, learnql::query::Field< T, FieldType >::Field.