learnql::core::Table::Iterator
using learnql::core::Table< T, BatchSize >::Iterator::iterator_category = std::forward_iterator_tag
using learnql::core::Table< T, BatchSize >::Iterator::value_type = T
using learnql::core::Table< T, BatchSize >::Iterator::difference_type = std::ptrdiff_t
using learnql::core::Table< T, BatchSize >::Iterator::pointer = const T*
using learnql::core::Table< T, BatchSize >::Iterator::reference = const T&
using learnql::core::Table< T, BatchSize >::Iterator::batch_iterator_type = index::BatchIterator<primary_key_type, RecordId, BatchSize>
const Table* learnql::core::Table< T, BatchSize >::Iterator::table_
std::shared_ptr<batch_iterator_type> learnql::core::Table< T, BatchSize >::Iterator::batch_iter_
std::vector<std::pair<primary_key_type, RecordId> > learnql::core::Table< T, BatchSize >::Iterator::current_batch_
std::size_t learnql::core::Table< T, BatchSize >::Iterator::batch_index_
T learnql::core::Table< T, BatchSize >::Iterator::current_
bool learnql::core::Table< T, BatchSize >::Iterator::current_loaded_
bool learnql::core::Table< T, BatchSize >::Iterator::is_end_
void learnql::core::Table< T, BatchSize >::Iterator::load_current() const
void learnql::core::Table< T, BatchSize >::Iterator::load_next_batch() const
learnql::core::Table< T, BatchSize >::Iterator::Iterator(const Table *table, std::shared_ptr< batch_iterator_type > batch_iter, bool is_end)
References learnql::core::Table< T, BatchSize >::Table.
Referenced by learnql::core::Table< T, BatchSize >::Iterator::operator!=, learnql::core::Table< T, BatchSize >::Iterator::operator++, learnql::core::Table< T, BatchSize >::Iterator::operator++, learnql::core::Table< T, BatchSize >::Iterator::operator==.
reference learnql::core::Table< T, BatchSize >::Iterator::operator*() const
pointer learnql::core::Table< T, BatchSize >::Iterator::operator->() const
Iterator & learnql::core::Table< T, BatchSize >::Iterator::operator++()
References learnql::core::Table< T, BatchSize >::Iterator::Iterator.
Iterator learnql::core::Table< T, BatchSize >::Iterator::operator++(int)
References learnql::core::Table< T, BatchSize >::Iterator::Iterator.
bool learnql::core::Table< T, BatchSize >::Iterator::operator==(const Iterator &other) const
References learnql::core::Table< T, BatchSize >::Iterator::Iterator.
bool learnql::core::Table< T, BatchSize >::Iterator::operator!=(const Iterator &other) const
References learnql::core::Table< T, BatchSize >::Iterator::Iterator.