learnql::index::MultiValueSecondaryIndex
using learnql::index::MultiValueSecondaryIndex< T, FieldType >::getter_type = std::function<FieldType(const T&)>
using learnql::index::MultiValueSecondaryIndex< T, FieldType >::map_type = std::unordered_map<FieldType, std::vector<core::RecordId>>
std::string learnql::index::MultiValueSecondaryIndex< T, FieldType >::field_name_
getter_type learnql::index::MultiValueSecondaryIndex< T, FieldType >::getter_
map_type learnql::index::MultiValueSecondaryIndex< T, FieldType >::index_
learnql::index::MultiValueSecondaryIndex< T, FieldType >::MultiValueSecondaryIndex(std::string field_name, getter_type getter)
Constructs a multi-value secondary index.
field_name Name of the field being indexed getter Function to extract the field value
References learnql::index::MultiValueSecondaryIndex< T, FieldType >::field_name.
void learnql::index::MultiValueSecondaryIndex< T, FieldType >::insert(const T &record, const core::RecordId &rid)
Inserts a record into the index.
record The record rid Record ID
Referenced by learnql::index::MultiValueSecondaryIndex< T, FieldType >::update.
std::vector< core::RecordId > learnql::index::MultiValueSecondaryIndex< T, FieldType >::find(const FieldType &value) const
Finds all RecordIds for a given field value.
value The field value to search for Vector of RecordIds (may be empty if not found)
bool learnql::index::MultiValueSecondaryIndex< T, FieldType >::remove(const T &record, const core::RecordId &rid)
Removes a specific record from the index.
record The record rid Record ID true if removed
Referenced by learnql::index::MultiValueSecondaryIndex< T, FieldType >::update.
void learnql::index::MultiValueSecondaryIndex< T, FieldType >::update(const T &old_record, const T &new_record, const core::RecordId &rid)
Updates the index when a record changes.
old_record The old record new_record The new record rid Record ID
References learnql::index::MultiValueSecondaryIndex< T, FieldType >::insert, learnql::index::MultiValueSecondaryIndex< T, FieldType >::remove.
const std::string & learnql::index::MultiValueSecondaryIndex< T, FieldType >::field_name() const noexcept
Gets the field name.
Referenced by learnql::index::MultiValueSecondaryIndex< T, FieldType >::MultiValueSecondaryIndex.
std::size_t learnql::index::MultiValueSecondaryIndex< T, FieldType >::size() const noexcept
Gets the number of unique values in the index.
std::size_t learnql::index::MultiValueSecondaryIndex< T, FieldType >::total_records() const noexcept
Gets the total number of indexed records.
void learnql::index::MultiValueSecondaryIndex< T, FieldType >::clear()
Clears the index.