learnql::meta
FieldType
using learnql::meta::property_return_type = std::conditional_t< std::is_fundamental_v<T> || (sizeof(T) <= sizeof(void*) && std::is_trivially_copyable_v<T>), T, const T& >
Type trait to determine the appropriate return type for a property getter.
Small, trivially copyable types (like int, double) are returned by value. Larger types (like std::string) are returned by const reference. T The property type
using learnql::meta::property_param_type = std::conditional_t< std::is_fundamental_v<T>, T, const T& >
Type trait to determine the appropriate parameter type for a property setter.
Fundamental types are passed by value. Non-fundamental types are passed by const reference. T The property type
T learnql::meta::deserialize_property(Reader &reader)
Helper function to deserialize a property based on its type.
Dispatches to the appropriate BinaryReader method: std::string -> read_string() Arithmetic types -> read<T>() Custom types -> read_custom<T>() T The property type Reader The reader type reader The binary reader The deserialized value
const char * learnql::meta::type_name()
Compile-time type name helper Maps C++ types to string representations for reflection.
Referenced by learnql::meta::TypeRegistry::get_type_info_by_name, learnql::meta::TypeRegistry::is_registered, learnql::meta::TypeRegistry::register_type_by_name, learnql::meta::PropertyMeta< Class, Type, IsPK >::type_string, learnql::meta::TypeInfo::TypeInfo.
std::string learnql::meta::field_type_to_string(FieldType type)
Converts FieldType to string.
References Bool, Custom, Double, Float, Int16, Int32, Int64, Int8, String, UInt16, UInt32, UInt64, UInt8.