learnql::storage::PageHeader
std::array<char, 4> learnql::storage::PageHeader::magic
Magic number for validation.
Referenced by is_valid, PageHeader.
uint64_t learnql::storage::PageHeader::page_id
Unique page identifier.
Referenced by PageHeader.
PageType learnql::storage::PageHeader::page_type
Type of page.
Referenced by PageHeader.
uint8_t learnql::storage::PageHeader::version
Format version.
Referenced by PageHeader.
uint16_t learnql::storage::PageHeader::record_count
Number of records in this page.
Referenced by PageHeader.
uint16_t learnql::storage::PageHeader::free_space_offset
Offset to free space.
Referenced by PageHeader.
uint64_t learnql::storage::PageHeader::next_page_id
Next page in chain (0 = none).
Referenced by PageHeader.
uint32_t learnql::storage::PageHeader::checksum
CRC32 checksum.
Referenced by PageHeader.
std::array<uint8_t, 34> learnql::storage::PageHeader::reserved
Reserved for future use.
Referenced by PageHeader.
learnql::storage::PageHeader::PageHeader() noexcept
Default constructor - initializes a free page.
References checksum, free_space_offset, magic, learnql::storage::MAGIC_NUMBER, next_page_id, page_id, page_type, PageHeader, record_count, reserved, version.
Referenced by operator<=>, PageHeader.
bool learnql::storage::PageHeader::is_valid() const noexcept
Validates the magic number.
true if magic number is valid
References magic, learnql::storage::MAGIC_NUMBER.
Referenced by learnql::storage::StorageEngine::read_page.
auto learnql::storage::PageHeader::operator<=>(const PageHeader &other) const noexcept=default
Three-way comparison for page headers.
References PageHeader.