learnql::core::RecordId
uint64_t learnql::core::RecordId::page_id
Page where record is stored.
Referenced by learnql::index::PersistentMultiValueSecondaryIndex< T, FieldType >::insert, is_valid, RecordId, learnql::index::PersistentMultiValueSecondaryIndex< T, FieldType >::remove, learnql::index::PersistentMultiValueSecondaryIndex< T, FieldType >::update.
uint32_t learnql::core::RecordId::slot
Slot within the page.
Referenced by RecordId.
learnql::core::RecordId::RecordId() noexcept
Default constructor - creates invalid ID.
References page_id, slot.
Referenced by invalid, operator<=>, operator==.
learnql::core::RecordId::RecordId(uint64_t pid, uint32_t s) noexcept
Constructs a record ID.
pid Page ID s Slot number
bool learnql::core::RecordId::is_valid() const noexcept
Checks if the ID is valid.
true if both page_id and slot are non-zero
References page_id.
auto learnql::core::RecordId::operator<=>(const RecordId &) const noexcept=default
Three-way comparison.
References RecordId.
bool learnql::core::RecordId::operator==(const RecordId &) const noexcept=default
Equality comparison.
References RecordId.
static constexpr RecordId learnql::core::RecordId::invalid() noexcept
Creates an invalid record ID.
References RecordId.